### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by vermiculus** [skeeto/transcription-mode#1]
``` lisp
(transcription-mode :repo "skeeto/transcription-mode"
                    :fetcher github)
```

This would be the appropriate code, presuming you want it on MELPA.

**Comment by skeeto** [comment]
Are you or anyone you know using this mode? I hastily wrote it to assist in a single transcription I did last year, but otherwise haven't advertised it in any way.

**Comment by vermiculus** [comment]
Well, you showed up on a google search :smile: I have an old friend who is doing a linguistics thesis and he needs to transcribe several six-speaker Skype recordings. He was looking around for tools, I suggested Emacs, and he embraced the idea of this editor that could be made to be a transcription-specific program :smile: (The challenge, perhaps, is convincing his mentor.)

I even went ahead and created [some input functions](https://gist.github.com/vermiculus/a8b3446c42767351cef7) ([demo](https://youtu.be/8WH8nBYReJQ?t=50s)) to assist with the process. Your minor mode is a perfect companion for it.

**Comment by vermiculus** [comment]
It may even make sense to merge the two into one package, come to think of it. If you're alright with that.

**Comment by skeeto** [comment]
Do you mean absorbing transcription-mode into your dialogger.el? I consider transcription-mode to be in the public domain, so you're free to do anything you like with it, no strings attached.

**Comment by vermiculus** [comment]
Either way – I'll take that on. If that sounds good to you, it'd be best not to put two versions of the same package on MELPA, so I guess this issue is moot now. Thanks for making this available! You never know who can get some use out of it :)

**Comment by vermiculus** [comment]
Would you be okay if I re-licensed the work under GPLv3? I'll link back to this repository in the code.

**Comment by skeeto** [comment]
While I think using the GPL with Emacs extensions is pointless (Who's
threatening to redistribute Elisp code in proprietary form?), that's
still fine with me. It's a bit awkward since technically it's already in
the public domain and can't be backed out into a copyright license, but
I'm guessing you're just avoiding having to mark off my stuff as being
different, which is fine.

I'll link to your repository from my README, too.

**Comment by vermiculus** [comment]
Well, it's unfortunately required if the code wants to make it into the GNU ELPA. Legal protection for the FSF and all that jazz.

**Comment by skeeto** [comment]
GNU's ELPA requires copyright assignment, which is more involved than
just using the GPL, but MELPA doesn't have any such requirement. All the
MELPA packages I maintain are also in the public domain.
